/**
 * Demo registry (AUTOGENERATED by /tmp/regenerate_registry.py — do not edit
 * by hand). Maps every condition demo slug to its component.
 *
 * Demo components receive only the selected view mode; auditor framing lives
 * in `DemoShell`.
 */

import type { ComponentType } from "react";

import type { ViewMode } from "@/components/demos/demo-shell";

import { ActivityMessagesCond1 } from "./demos/activity-messages-condition-1";
import { ActivityMessagesCond2 } from "./demos/activity-messages-condition-2";
import { ActivityMessagesCond3 } from "./demos/activity-messages-condition-3";
import { AddictiveDesignCond1 } from "./demos/addictive-design-condition-1";
import { AddictiveDesignCond2 } from "./demos/addictive-design-condition-2";
import { AddictiveDesignCond3 } from "./demos/addictive-design-condition-3";
import { AddressBookLeechingCond1 } from "./demos/address-book-leeching-condition-1";
import { AddressBookLeechingCond2 } from "./demos/address-book-leeching-condition-2";
import { AddressBookLeechingCond3 } from "./demos/address-book-leeching-condition-3";
import { AutoPlayCond1 } from "./demos/auto-play-condition-1";
import { AutoPlayCond2 } from "./demos/auto-play-condition-2";
import { AutoPlayCond3 } from "./demos/auto-play-condition-3";
import { AutomaticAcceptThirdPartyTermCond1 } from "./demos/automatic-accept-third-party-term-condition-1";
import { AutomaticAcceptThirdPartyTermCond2 } from "./demos/automatic-accept-third-party-term-condition-2";
import { AutomaticAcceptThirdPartyTermCond3 } from "./demos/automatic-accept-third-party-term-condition-3";
import { AutomatingTheUserAwayCond1 } from "./demos/automating-the-user-away-condition-1";
import { AutomatingTheUserAwayCond2 } from "./demos/automating-the-user-away-condition-2";
import { AutomatingTheUserAwayCond3 } from "./demos/automating-the-user-away-condition-3";
import { BadDefaultsPreselectionCond1 } from "./demos/bad-defaults-preselection-condition-1";
import { BadDefaultsPreselectionCond2 } from "./demos/bad-defaults-preselection-condition-2";
import { BadDefaultsPreselectionCond3 } from "./demos/bad-defaults-preselection-condition-3";
import { BundlingCond1 } from "./demos/bundling-condition-1";
import { BundlingCond2 } from "./demos/bundling-condition-2";
import { BundlingCond3 } from "./demos/bundling-condition-3";
import { ChoiceOverloadCond1 } from "./demos/choice-overload-condition-1";
import { ChoiceOverloadCond2 } from "./demos/choice-overload-condition-2";
import { ChoiceOverloadCond3 } from "./demos/choice-overload-condition-3";
import { ComplexLanguageCond1 } from "./demos/complex-language-condition-1";
import { ComplexLanguageCond2 } from "./demos/complex-language-condition-2";
import { ComplexLanguageCond3 } from "./demos/complex-language-condition-3";
import { ConfirmshamingCond1 } from "./demos/confirmshaming-condition-1";
import { ConfirmshamingCond2 } from "./demos/confirmshaming-condition-2";
import { ConfirmshamingCond3 } from "./demos/confirmshaming-condition-3";
import { ConflictingInformationCond1 } from "./demos/conflicting-information-condition-1";
import { ConflictingInformationCond2 } from "./demos/conflicting-information-condition-2";
import { ConflictingInformationCond3 } from "./demos/conflicting-information-condition-3";
import { CountdownOnAdsCond1 } from "./demos/countdown-on-ads-condition-1";
import { CountdownOnAdsCond2 } from "./demos/countdown-on-ads-condition-2";
import { CountdownOnAdsCond3 } from "./demos/countdown-on-ads-condition-3";
import { CountdownTimerCond1 } from "./demos/countdown-timer-condition-1";
import { CountdownTimerCond2 } from "./demos/countdown-timer-condition-2";
import { CountdownTimerCond3 } from "./demos/countdown-timer-condition-3";
import { CustomisationCond1 } from "./demos/customisation-condition-1";
import { CustomisationCond2 } from "./demos/customisation-condition-2";
import { CustomisationCond3 } from "./demos/customisation-condition-3";
import { CutenessCond1 } from "./demos/cuteness-condition-1";
import { CutenessCond2 } from "./demos/cuteness-condition-2";
import { CutenessCond3 } from "./demos/cuteness-condition-3";
import { DeadEndCond1 } from "./demos/dead-end-condition-1";
import { DeadEndCond2 } from "./demos/dead-end-condition-2";
import { DeadEndCond3 } from "./demos/dead-end-condition-3";
import { DisguisedAdCond1 } from "./demos/disguised-ad-condition-1";
import { DisguisedAdCond2 } from "./demos/disguised-ad-condition-2";
import { DisguisedAdCond3 } from "./demos/disguised-ad-condition-3";
import { DripPricingCond1 } from "./demos/drip-pricing-condition-1";
import { DripPricingCond2 } from "./demos/drip-pricing-condition-2";
import { DripPricingCond3 } from "./demos/drip-pricing-condition-3";
import { EncouragingAntiSocialBehaviorCond1 } from "./demos/encouraging-anti-social-behavior-condition-1";
import { EncouragingAntiSocialBehaviorCond2 } from "./demos/encouraging-anti-social-behavior-condition-2";
import { EncouragingAntiSocialBehaviorCond3 } from "./demos/encouraging-anti-social-behavior-condition-3";
import { EndorsementAndTestimonialsCond1 } from "./demos/endorsement-and-testimonials-condition-1";
import { EndorsementAndTestimonialsCond2 } from "./demos/endorsement-and-testimonials-condition-2";
import { EndorsementAndTestimonialsCond3 } from "./demos/endorsement-and-testimonials-condition-3";
import { FalseHierarchyCond1 } from "./demos/false-hierarchy-condition-1";
import { FalseHierarchyCond2 } from "./demos/false-hierarchy-condition-2";
import { FalseHierarchyCond3 } from "./demos/false-hierarchy-condition-3";
import { FearOfMissingOutFomoCond1 } from "./demos/fear-of-missing-out-fomo-condition-1";
import { FearOfMissingOutFomoCond2 } from "./demos/fear-of-missing-out-fomo-condition-2";
import { FearOfMissingOutFomoCond3 } from "./demos/fear-of-missing-out-fomo-condition-3";
import { FeedforwardAmbiguityCond1 } from "./demos/feedforward-ambiguity-condition-1";
import { FeedforwardAmbiguityCond2 } from "./demos/feedforward-ambiguity-condition-2";
import { FeedforwardAmbiguityCond3 } from "./demos/feedforward-ambiguity-condition-3";
import { ForcedContinuityCond1 } from "./demos/forced-continuity-condition-1";
import { ForcedContinuityCond2 } from "./demos/forced-continuity-condition-2";
import { ForcedContinuityCond3 } from "./demos/forced-continuity-condition-3";
import { ForcedGracePeriodCond1 } from "./demos/forced-grace-period-condition-1";
import { ForcedGracePeriodCond2 } from "./demos/forced-grace-period-condition-2";
import { ForcedGracePeriodCond3 } from "./demos/forced-grace-period-condition-3";
import { ForcedRegistrationCond1 } from "./demos/forced-registration-condition-1";
import { ForcedRegistrationCond2 } from "./demos/forced-registration-condition-2";
import { ForcedRegistrationCond3 } from "./demos/forced-registration-condition-3";
import { FriendSpamCond1 } from "./demos/friend-spam-condition-1";
import { FriendSpamCond2 } from "./demos/friend-spam-condition-2";
import { FriendSpamCond3 } from "./demos/friend-spam-condition-3";
import { GrantingAndInteractionCond1 } from "./demos/granting-and-interaction-condition-1";
import { GrantingAndInteractionCond2 } from "./demos/granting-and-interaction-condition-2";
import { GrantingAndInteractionCond3 } from "./demos/granting-and-interaction-condition-3";
import { GrindingCond1 } from "./demos/grinding-condition-1";
import { GrindingCond2 } from "./demos/grinding-condition-2";
import { GrindingCond3 } from "./demos/grinding-condition-3";
import { HiddenInformationCond1 } from "./demos/hidden-information-condition-1";
import { HiddenInformationCond2 } from "./demos/hidden-information-condition-2";
import { HiddenInformationCond3 } from "./demos/hidden-information-condition-3";
import { HighDemandCond1 } from "./demos/high-demand-condition-1";
import { HighDemandCond2 } from "./demos/high-demand-condition-2";
import { HighDemandCond3 } from "./demos/high-demand-condition-3";
import { ImmortalAccountsCond1 } from "./demos/immortal-accounts-condition-1";
import { ImmortalAccountsCond2 } from "./demos/immortal-accounts-condition-2";
import { ImmortalAccountsCond3 } from "./demos/immortal-accounts-condition-3";
import { InfiniteScrollingCond1 } from "./demos/infinite-scrolling-condition-1";
import { InfiniteScrollingCond2 } from "./demos/infinite-scrolling-condition-2";
import { InfiniteScrollingCond3 } from "./demos/infinite-scrolling-condition-3";
import { InformationWithoutContextCond1 } from "./demos/information-without-context-condition-1";
import { InformationWithoutContextCond2 } from "./demos/information-without-context-condition-2";
import { InformationWithoutContextCond3 } from "./demos/information-without-context-condition-3";
import { IntermediateCurrencyCond1 } from "./demos/intermediate-currency-condition-1";
import { IntermediateCurrencyCond2 } from "./demos/intermediate-currency-condition-2";
import { IntermediateCurrencyCond3 } from "./demos/intermediate-currency-condition-3";
import { LabyrinthineNavigationCond1 } from "./demos/labyrinthine-navigation-condition-1";
import { LabyrinthineNavigationCond2 } from "./demos/labyrinthine-navigation-condition-2";
import { LabyrinthineNavigationCond3 } from "./demos/labyrinthine-navigation-condition-3";
import { LimitedTimeMessageCond1 } from "./demos/limited-time-message-condition-1";
import { LimitedTimeMessageCond2 } from "./demos/limited-time-message-condition-2";
import { LimitedTimeMessageCond3 } from "./demos/limited-time-message-condition-3";
import { LowStockCond1 } from "./demos/low-stock-condition-1";
import { LowStockCond2 } from "./demos/low-stock-condition-2";
import { LowStockCond3 } from "./demos/low-stock-condition-3";
import { ParasocialPressureCond1 } from "./demos/parasocial-pressure-condition-1";
import { ParasocialPressureCond2 } from "./demos/parasocial-pressure-condition-2";
import { ParasocialPressureCond3 } from "./demos/parasocial-pressure-condition-3";
import { PayToAvoidCond1 } from "./demos/pay-to-avoid-condition-1";
import { PayToAvoidCond2 } from "./demos/pay-to-avoid-condition-2";
import { PayToAvoidCond3 } from "./demos/pay-to-avoid-condition-3";
import { PayToPlayCond1 } from "./demos/pay-to-play-condition-1";
import { PayToPlayCond2 } from "./demos/pay-to-play-condition-2";
import { PayToPlayCond3 } from "./demos/pay-to-play-condition-3";
import { PersuasiveLanguageCond1 } from "./demos/persuasive-language-condition-1";
import { PersuasiveLanguageCond2 } from "./demos/persuasive-language-condition-2";
import { PersuasiveLanguageCond3 } from "./demos/persuasive-language-condition-3";
import { PlainEvilCond1 } from "./demos/plain-evil-condition-1";
import { PlainEvilCond2 } from "./demos/plain-evil-condition-2";
import { PlainEvilCond3 } from "./demos/plain-evil-condition-3";
import { PlayingByAppointmentCond1 } from "./demos/playing-by-appointment-condition-1";
import { PlayingByAppointmentCond2 } from "./demos/playing-by-appointment-condition-2";
import { PlayingByAppointmentCond3 } from "./demos/playing-by-appointment-condition-3";
import { PositiveOrNegativeFramingCond1 } from "./demos/positive-or-negative-framing-condition-1";
import { PositiveOrNegativeFramingCond2 } from "./demos/positive-or-negative-framing-condition-2";
import { PositiveOrNegativeFramingCond3 } from "./demos/positive-or-negative-framing-condition-3";
import { PreDeliveredContentCond1 } from "./demos/pre-delivered-content-condition-1";
import { PreDeliveredContentCond2 } from "./demos/pre-delivered-content-condition-2";
import { PreDeliveredContentCond3 } from "./demos/pre-delivered-content-condition-3";
import { PressuredSellingCond1 } from "./demos/pressured-selling-condition-1";
import { PressuredSellingCond2 } from "./demos/pressured-selling-condition-2";
import { PressuredSellingCond3 } from "./demos/pressured-selling-condition-3";
import { PriceComparisonPreventionCond1 } from "./demos/price-comparison-prevention-condition-1";
import { PriceComparisonPreventionCond2 } from "./demos/price-comparison-prevention-condition-2";
import { PriceComparisonPreventionCond3 } from "./demos/price-comparison-prevention-condition-3";
import { PrivacyMazeCond1 } from "./demos/privacy-maze-condition-1";
import { PrivacyMazeCond2 } from "./demos/privacy-maze-condition-2";
import { PrivacyMazeCond3 } from "./demos/privacy-maze-condition-3";
import { PrivacyZuckeringCond1 } from "./demos/privacy-zuckering-condition-1";
import { PrivacyZuckeringCond2 } from "./demos/privacy-zuckering-condition-2";
import { PrivacyZuckeringCond3 } from "./demos/privacy-zuckering-condition-3";
import { PsychologicalTricksCond1 } from "./demos/psychological-tricks-condition-1";
import { PsychologicalTricksCond2 } from "./demos/psychological-tricks-condition-2";
import { PsychologicalTricksCond3 } from "./demos/psychological-tricks-condition-3";
import { PullToRefreshCond1 } from "./demos/pull-to-refresh-condition-1";
import { PullToRefreshCond2 } from "./demos/pull-to-refresh-condition-2";
import { PullToRefreshCond3 } from "./demos/pull-to-refresh-condition-3";
import { ReducedFrictionCond1 } from "./demos/reduced-friction-condition-1";
import { ReducedFrictionCond2 } from "./demos/reduced-friction-condition-2";
import { ReducedFrictionCond3 } from "./demos/reduced-friction-condition-3";
import { ReferencePricingCond1 } from "./demos/reference-pricing-condition-1";
import { ReferencePricingCond2 } from "./demos/reference-pricing-condition-2";
import { ReferencePricingCond3 } from "./demos/reference-pricing-condition-3";
import { SmallOrMovingCloseButtonCond1 } from "./demos/small-or-moving-close-button-condition-1";
import { SmallOrMovingCloseButtonCond2 } from "./demos/small-or-moving-close-button-condition-2";
import { SmallOrMovingCloseButtonCond3 } from "./demos/small-or-moving-close-button-condition-3";
import { SneakIntoBasketCond1 } from "./demos/sneak-into-basket-condition-1";
import { SneakIntoBasketCond2 } from "./demos/sneak-into-basket-condition-2";
import { SneakIntoBasketCond3 } from "./demos/sneak-into-basket-condition-3";
import { SocialPyramidCond1 } from "./demos/social-pyramid-condition-1";
import { SocialPyramidCond2 } from "./demos/social-pyramid-condition-2";
import { SocialPyramidCond3 } from "./demos/social-pyramid-condition-3";
import { TrickQuestionsCond1 } from "./demos/trick-questions-condition-1";
import { TrickQuestionsCond2 } from "./demos/trick-questions-condition-2";
import { TrickQuestionsCond3 } from "./demos/trick-questions-condition-3";
import { VisualProminenceCond1 } from "./demos/visual-prominence-condition-1";
import { VisualProminenceCond2 } from "./demos/visual-prominence-condition-2";
import { VisualProminenceCond3 } from "./demos/visual-prominence-condition-3";
import { WatchAdsToUnlockFeaturesCond1 } from "./demos/watch-ads-to-unlock-features-condition-1";
import { WatchAdsToUnlockFeaturesCond2 } from "./demos/watch-ads-to-unlock-features-condition-2";
import { WatchAdsToUnlockFeaturesCond3 } from "./demos/watch-ads-to-unlock-features-condition-3";
import { WrongLanguageCond1 } from "./demos/wrong-language-condition-1";
import { WrongLanguageCond2 } from "./demos/wrong-language-condition-2";
import { WrongLanguageCond3 } from "./demos/wrong-language-condition-3";

export interface DemoProps {
  /** "user" shows the product UI; "auditor" adds comparison context. */
  mode?: ViewMode;
}

export type DemoComponent = ComponentType<DemoProps>;

const registry: Record<string, DemoComponent> = {
  "activity-messages-condition-1": ActivityMessagesCond1,
  "activity-messages-condition-2": ActivityMessagesCond2,
  "activity-messages-condition-3": ActivityMessagesCond3,
  "addictive-design-condition-1": AddictiveDesignCond1,
  "addictive-design-condition-2": AddictiveDesignCond2,
  "addictive-design-condition-3": AddictiveDesignCond3,
  "address-book-leeching-condition-1": AddressBookLeechingCond1,
  "address-book-leeching-condition-2": AddressBookLeechingCond2,
  "address-book-leeching-condition-3": AddressBookLeechingCond3,
  "auto-play-condition-1": AutoPlayCond1,
  "auto-play-condition-2": AutoPlayCond2,
  "auto-play-condition-3": AutoPlayCond3,
  "automatic-accept-third-party-term-condition-1": AutomaticAcceptThirdPartyTermCond1,
  "automatic-accept-third-party-term-condition-2": AutomaticAcceptThirdPartyTermCond2,
  "automatic-accept-third-party-term-condition-3": AutomaticAcceptThirdPartyTermCond3,
  "automating-the-user-away-condition-1": AutomatingTheUserAwayCond1,
  "automating-the-user-away-condition-2": AutomatingTheUserAwayCond2,
  "automating-the-user-away-condition-3": AutomatingTheUserAwayCond3,
  "bad-defaults-preselection-condition-1": BadDefaultsPreselectionCond1,
  "bad-defaults-preselection-condition-2": BadDefaultsPreselectionCond2,
  "bad-defaults-preselection-condition-3": BadDefaultsPreselectionCond3,
  "bundling-condition-1": BundlingCond1,
  "bundling-condition-2": BundlingCond2,
  "bundling-condition-3": BundlingCond3,
  "choice-overload-condition-1": ChoiceOverloadCond1,
  "choice-overload-condition-2": ChoiceOverloadCond2,
  "choice-overload-condition-3": ChoiceOverloadCond3,
  "complex-language-condition-1": ComplexLanguageCond1,
  "complex-language-condition-2": ComplexLanguageCond2,
  "complex-language-condition-3": ComplexLanguageCond3,
  "confirmshaming-condition-1": ConfirmshamingCond1,
  "confirmshaming-condition-2": ConfirmshamingCond2,
  "confirmshaming-condition-3": ConfirmshamingCond3,
  "conflicting-information-condition-1": ConflictingInformationCond1,
  "conflicting-information-condition-2": ConflictingInformationCond2,
  "conflicting-information-condition-3": ConflictingInformationCond3,
  "countdown-on-ads-condition-1": CountdownOnAdsCond1,
  "countdown-on-ads-condition-2": CountdownOnAdsCond2,
  "countdown-on-ads-condition-3": CountdownOnAdsCond3,
  "countdown-timer-condition-1": CountdownTimerCond1,
  "countdown-timer-condition-2": CountdownTimerCond2,
  "countdown-timer-condition-3": CountdownTimerCond3,
  "customisation-condition-1": CustomisationCond1,
  "customisation-condition-2": CustomisationCond2,
  "customisation-condition-3": CustomisationCond3,
  "cuteness-condition-1": CutenessCond1,
  "cuteness-condition-2": CutenessCond2,
  "cuteness-condition-3": CutenessCond3,
  "dead-end-condition-1": DeadEndCond1,
  "dead-end-condition-2": DeadEndCond2,
  "dead-end-condition-3": DeadEndCond3,
  "disguised-ad-condition-1": DisguisedAdCond1,
  "disguised-ad-condition-2": DisguisedAdCond2,
  "disguised-ad-condition-3": DisguisedAdCond3,
  "drip-pricing-condition-1": DripPricingCond1,
  "drip-pricing-condition-2": DripPricingCond2,
  "drip-pricing-condition-3": DripPricingCond3,
  "encouraging-anti-social-behavior-condition-1": EncouragingAntiSocialBehaviorCond1,
  "encouraging-anti-social-behavior-condition-2": EncouragingAntiSocialBehaviorCond2,
  "encouraging-anti-social-behavior-condition-3": EncouragingAntiSocialBehaviorCond3,
  "endorsement-and-testimonials-condition-1": EndorsementAndTestimonialsCond1,
  "endorsement-and-testimonials-condition-2": EndorsementAndTestimonialsCond2,
  "endorsement-and-testimonials-condition-3": EndorsementAndTestimonialsCond3,
  "false-hierarchy-condition-1": FalseHierarchyCond1,
  "false-hierarchy-condition-2": FalseHierarchyCond2,
  "false-hierarchy-condition-3": FalseHierarchyCond3,
  "fear-of-missing-out-fomo-condition-1": FearOfMissingOutFomoCond1,
  "fear-of-missing-out-fomo-condition-2": FearOfMissingOutFomoCond2,
  "fear-of-missing-out-fomo-condition-3": FearOfMissingOutFomoCond3,
  "feedforward-ambiguity-condition-1": FeedforwardAmbiguityCond1,
  "feedforward-ambiguity-condition-2": FeedforwardAmbiguityCond2,
  "feedforward-ambiguity-condition-3": FeedforwardAmbiguityCond3,
  "forced-continuity-condition-1": ForcedContinuityCond1,
  "forced-continuity-condition-2": ForcedContinuityCond2,
  "forced-continuity-condition-3": ForcedContinuityCond3,
  "forced-grace-period-condition-1": ForcedGracePeriodCond1,
  "forced-grace-period-condition-2": ForcedGracePeriodCond2,
  "forced-grace-period-condition-3": ForcedGracePeriodCond3,
  "forced-registration-condition-1": ForcedRegistrationCond1,
  "forced-registration-condition-2": ForcedRegistrationCond2,
  "forced-registration-condition-3": ForcedRegistrationCond3,
  "friend-spam-condition-1": FriendSpamCond1,
  "friend-spam-condition-2": FriendSpamCond2,
  "friend-spam-condition-3": FriendSpamCond3,
  "granting-and-interaction-condition-1": GrantingAndInteractionCond1,
  "granting-and-interaction-condition-2": GrantingAndInteractionCond2,
  "granting-and-interaction-condition-3": GrantingAndInteractionCond3,
  "grinding-condition-1": GrindingCond1,
  "grinding-condition-2": GrindingCond2,
  "grinding-condition-3": GrindingCond3,
  "hidden-information-condition-1": HiddenInformationCond1,
  "hidden-information-condition-2": HiddenInformationCond2,
  "hidden-information-condition-3": HiddenInformationCond3,
  "high-demand-condition-1": HighDemandCond1,
  "high-demand-condition-2": HighDemandCond2,
  "high-demand-condition-3": HighDemandCond3,
  "immortal-accounts-condition-1": ImmortalAccountsCond1,
  "immortal-accounts-condition-2": ImmortalAccountsCond2,
  "immortal-accounts-condition-3": ImmortalAccountsCond3,
  "infinite-scrolling-condition-1": InfiniteScrollingCond1,
  "infinite-scrolling-condition-2": InfiniteScrollingCond2,
  "infinite-scrolling-condition-3": InfiniteScrollingCond3,
  "information-without-context-condition-1": InformationWithoutContextCond1,
  "information-without-context-condition-2": InformationWithoutContextCond2,
  "information-without-context-condition-3": InformationWithoutContextCond3,
  "intermediate-currency-condition-1": IntermediateCurrencyCond1,
  "intermediate-currency-condition-2": IntermediateCurrencyCond2,
  "intermediate-currency-condition-3": IntermediateCurrencyCond3,
  "labyrinthine-navigation-condition-1": LabyrinthineNavigationCond1,
  "labyrinthine-navigation-condition-2": LabyrinthineNavigationCond2,
  "labyrinthine-navigation-condition-3": LabyrinthineNavigationCond3,
  "limited-time-message-condition-1": LimitedTimeMessageCond1,
  "limited-time-message-condition-2": LimitedTimeMessageCond2,
  "limited-time-message-condition-3": LimitedTimeMessageCond3,
  "low-stock-condition-1": LowStockCond1,
  "low-stock-condition-2": LowStockCond2,
  "low-stock-condition-3": LowStockCond3,
  "parasocial-pressure-condition-1": ParasocialPressureCond1,
  "parasocial-pressure-condition-2": ParasocialPressureCond2,
  "parasocial-pressure-condition-3": ParasocialPressureCond3,
  "pay-to-avoid-condition-1": PayToAvoidCond1,
  "pay-to-avoid-condition-2": PayToAvoidCond2,
  "pay-to-avoid-condition-3": PayToAvoidCond3,
  "pay-to-play-condition-1": PayToPlayCond1,
  "pay-to-play-condition-2": PayToPlayCond2,
  "pay-to-play-condition-3": PayToPlayCond3,
  "persuasive-language-condition-1": PersuasiveLanguageCond1,
  "persuasive-language-condition-2": PersuasiveLanguageCond2,
  "persuasive-language-condition-3": PersuasiveLanguageCond3,
  "plain-evil-condition-1": PlainEvilCond1,
  "plain-evil-condition-2": PlainEvilCond2,
  "plain-evil-condition-3": PlainEvilCond3,
  "playing-by-appointment-condition-1": PlayingByAppointmentCond1,
  "playing-by-appointment-condition-2": PlayingByAppointmentCond2,
  "playing-by-appointment-condition-3": PlayingByAppointmentCond3,
  "positive-or-negative-framing-condition-1": PositiveOrNegativeFramingCond1,
  "positive-or-negative-framing-condition-2": PositiveOrNegativeFramingCond2,
  "positive-or-negative-framing-condition-3": PositiveOrNegativeFramingCond3,
  "pre-delivered-content-condition-1": PreDeliveredContentCond1,
  "pre-delivered-content-condition-2": PreDeliveredContentCond2,
  "pre-delivered-content-condition-3": PreDeliveredContentCond3,
  "pressured-selling-condition-1": PressuredSellingCond1,
  "pressured-selling-condition-2": PressuredSellingCond2,
  "pressured-selling-condition-3": PressuredSellingCond3,
  "price-comparison-prevention-condition-1": PriceComparisonPreventionCond1,
  "price-comparison-prevention-condition-2": PriceComparisonPreventionCond2,
  "price-comparison-prevention-condition-3": PriceComparisonPreventionCond3,
  "privacy-maze-condition-1": PrivacyMazeCond1,
  "privacy-maze-condition-2": PrivacyMazeCond2,
  "privacy-maze-condition-3": PrivacyMazeCond3,
  "privacy-zuckering-condition-1": PrivacyZuckeringCond1,
  "privacy-zuckering-condition-2": PrivacyZuckeringCond2,
  "privacy-zuckering-condition-3": PrivacyZuckeringCond3,
  "psychological-tricks-condition-1": PsychologicalTricksCond1,
  "psychological-tricks-condition-2": PsychologicalTricksCond2,
  "psychological-tricks-condition-3": PsychologicalTricksCond3,
  "pull-to-refresh-condition-1": PullToRefreshCond1,
  "pull-to-refresh-condition-2": PullToRefreshCond2,
  "pull-to-refresh-condition-3": PullToRefreshCond3,
  "reduced-friction-condition-1": ReducedFrictionCond1,
  "reduced-friction-condition-2": ReducedFrictionCond2,
  "reduced-friction-condition-3": ReducedFrictionCond3,
  "reference-pricing-condition-1": ReferencePricingCond1,
  "reference-pricing-condition-2": ReferencePricingCond2,
  "reference-pricing-condition-3": ReferencePricingCond3,
  "small-or-moving-close-button-condition-1": SmallOrMovingCloseButtonCond1,
  "small-or-moving-close-button-condition-2": SmallOrMovingCloseButtonCond2,
  "small-or-moving-close-button-condition-3": SmallOrMovingCloseButtonCond3,
  "sneak-into-basket-condition-1": SneakIntoBasketCond1,
  "sneak-into-basket-condition-2": SneakIntoBasketCond2,
  "sneak-into-basket-condition-3": SneakIntoBasketCond3,
  "social-pyramid-condition-1": SocialPyramidCond1,
  "social-pyramid-condition-2": SocialPyramidCond2,
  "social-pyramid-condition-3": SocialPyramidCond3,
  "trick-questions-condition-1": TrickQuestionsCond1,
  "trick-questions-condition-2": TrickQuestionsCond2,
  "trick-questions-condition-3": TrickQuestionsCond3,
  "visual-prominence-condition-1": VisualProminenceCond1,
  "visual-prominence-condition-2": VisualProminenceCond2,
  "visual-prominence-condition-3": VisualProminenceCond3,
  "watch-ads-to-unlock-features-condition-1": WatchAdsToUnlockFeaturesCond1,
  "watch-ads-to-unlock-features-condition-2": WatchAdsToUnlockFeaturesCond2,
  "watch-ads-to-unlock-features-condition-3": WatchAdsToUnlockFeaturesCond3,
  "wrong-language-condition-1": WrongLanguageCond1,
  "wrong-language-condition-2": WrongLanguageCond2,
  "wrong-language-condition-3": WrongLanguageCond3,
};

/** Get the static demo component for a pattern slug, or undefined. */
export function getDemo(slug: string): DemoComponent | undefined {
  return registry[slug];
}

